### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by arsenyspb** [stevenleeg/Minecraft-Log-Parser#10]
```
mclp /apps/prod-minecraft/logs/latest.log
  File "/usr/bin/mclp", line 96
    print "%2d) %s" % (counter, time)
                  ^
SyntaxError: invalid syntax
```

I'm on Python 2.7.5

Would be fantastic if you maintained this script ;-)

**Comment by stevenleeg** [comment]
Haha yeah, I don't think I have the capability to maintain this project anymore. Feel free to fork if you end up creating something new!
