### ISSUE TITLE
readme.md needs correction

### ISSUE THREAD

**Issue by jrogers512** [stevenleeg/Minecraft-Log-Parser#6]
End of readme.md says to call script with no arguments, which appears wrong.  Instead the filename of the server.log file should be called:

~/Minecraft-Log-Parser$ python parser.py 
Traceback (most recent call last):
  File "parser.py", line 10, in <module>
    if sys.argv[1]:
IndexError: list index out of range

**Comment by stevenleeg** [comment]
Got it. Thanks for letting me know!
