### ISSUE TITLE
fault on server crash

### ISSUE THREAD

**Issue by yodalee** [stevenleeg/Minecraft-Log-Parser#7]
If the server were closed unnaturally or it simply crashed, there will have no logout record of "user lost connection". Which will cause underestimate the using time.
suggest detect two more pattern:
"Starting minecraft server version"
"Stopping server"
and use the time as logout time of all user

**Comment by stevenleeg** [comment]
I've stopped running a Minecraft server for a while now so I don't have a server log to
test on. Could you upload an example to gist for me?

**Comment by yodalee** [comment]
https://dl.dropbox.com/u/3192346/server.log
I replace all ip to 111.111.111.111
and every user name to userx
you can see line 314, user4, 9 are online
but then server is closed, and no logout record.

**Comment by stevenleeg** [comment]
I think I got it. Go ahead and check the new code just to be sure.

**Comment by yodalee** [comment]
thx, I think it count time more accurately now
