### ISSUE TITLE
can't match special sign in username

### ISSUE THREAD

**Issue by yodalee** [stevenleeg/Minecraft-Log-Parser#8]
I got a friend who use the name "Yoooo+"
Since the regular expression didn't match +, the mclp didn't count his playing time
Suggestion that matching all printable character to player name

**Comment by stevenleeg** [comment]
@paris-ci Are there restrictions on names for real minecraft accounts?

**Comment by stevenleeg** [comment]
Ahh I see. Well as long as it doesn't screw anything up I'm fine with adding + to the username matching regex.

@lc85301 could you send me a relevant section of your server log to test with?
